# This docker-compose file is for local development only
version: "3.3"
services:
  rabbitmq:
    build: .
    ports:
      - target: 5672
        published: 5672
        mode: host
      - target: 15672
        published: 15672
        mode: host
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
